### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by 3bdrzk** [TeamChocoQuest/ChocolateQuestRepoured#160]
I tried to launch a server on Aternos with a custom modpack and CQR crashes the servuer.
here's the modlist : 

ActuallyAdditions-1.12.2-r151-2.jar
ActuallyBaubles-1.12-1.1.jar
AkashicTome-1.2-12.jar
AppleSkin-mc1.12-1.0.9.jar
AutoRegLib-1.3-32.jar
BaubleShulkerBoxes-1.12.2-4r.jar
Baublelicious-1.4.0-4.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
BuildingGadgets-2.8.2.jar
CTM-MC1.12.2-1.0.1.30.jar
CarryOn MC1.12.2 v1.12.3.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-1.0.1.44.jar
ChocolateQuestRepoured-1.12.2-1.12.0A.jar
CraftTweaker2-1.12-4.1.20.jar
FriendlyFire-1.12.2-1.5.12.jar
Hwyla-1.8.26-B41_1.12.2.jar
InventoryTweaks-1.63.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
Pam's HarvestCraft 1.12.2zg.jar
Patchouli-1.0-20.jar
Quark-r1.6-178.jar
Reliquary-1.12.2-1.3.4.796.jar
StorageDrawers-1.12.2-5.4.1.jar
VanillaFix-1.0.10-99.jar
YAMDA-1.0.2.jar
betternether-0.1.8.6.jar
extrautils2-1.12-1.9.9.jar
foamfix-0.10.10-1.12.2.jar
future-mc-0.1.13.jar
ironchest-1.12.2-7.0.72.847.jar
ironfurnaces-1.3.5.jar
jei_1.12.2-4.15.0.293.jar
journeymap-1.12.2-5.7.0.jar
llibrary-1.7.19-1.12.2.jar
mowziesmobs-1.5.4.jar
specialmobs-1.0.2_for_mc1.12.2.jar
stg-1.12.2-1.2.3.jar
twilightforest-1.12.2-3.10.1013-universal.jar

and the logs : 

https://mclo.gs/0J7Yaoq

and the crash report : 

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2020-03-19 13:18:33 CET
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
    at com.teamcqr.chocolatequestrepoured.init.ModItems$ItemRegistrationHandler.registerItems(ModItems.java:352)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_ItemRegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.model.ModelBiped
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 12 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.4.0-134-generic
  Java Version: 1.8.0_242, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 641328728 bytes (611 MB) / 1011875840 bytes (965 MB) up to 1398276096 bytes (1333 MB)
  JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1500M -Xms750M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 48 mods loaded, 48 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                 | Version                  | Source                                        | Signature                                |
       |:----- |:------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft          | 1.12.2                   | minecraft.jar                                 | None                                     |
       | LCH   | mcp                | 9.42                     | minecraft.jar                                 | None                                     |
       | LCH   | FML                | 8.0.99.99                | forge.jar                                     | None                                     |
       | LCH   | forge              | 14.23.5.2847             | forge.jar                                     | None                                     |
       | LCH   | openmodscore       | 0.12.2                   | minecraft.jar                                 | None                                     |
       | LCH   | foamfixcore        | 7.7.4                    | minecraft.jar                                 | None                                     |
       | LCH   | futuremccore       | 0.1.12                   | minecraft.jar                                 | None                                     |
       | LCH   | actuallyadditions  | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar           | None                                     |
       | LCH   | baubles            | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCH   | actuallybaubles    | 1.1                      | ActuallyBaubles-1.12-1.1.jar                  | None                                     |
       | LCH   | akashictome        | 1.2-12                   | AkashicTome-1.2-12.jar                        | None                                     |
       | LCH   | jei                | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                     | None                                     |
       | LCH   | appleskin          | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
       | LCH   | quark              | r1.6-178                 | Quark-r1.6-178.jar                            | None                                     |
       | LCH   | autoreglib         | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCH   | baublelicious      | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                     | None                                     |
       | LCH   | baubleshulkerboxes | 4r                       | BaubleShulkerBoxes-1.12.2-4r.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | betternether       | 0.1.8.6                  | betternether-0.1.8.6.jar                      | None                                     |
       | LCH   | buildinggadgets    | 2.8.2                    | BuildingGadgets-2.8.2.jar                     | None                                     |
       | LCH   | carryon            | 1.12.3                   | CarryOn MC1.12.2 v1.12.3.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCH   | chameleon          | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
       | LCH   | chisel             | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
       | LCH   | llibrary           | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | cqrepoured         | 1.12.1A                  | ChocolateQuestRepoured-1.12.2-1.12.1A.jar     | None                                     |
       | LCH   | crafttweaker       | 4.1.20                   | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
       | LCH   | crafttweakerjei    | 2.0.3                    | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
       | LCH   | extrautils2        | 1.0                      | extrautils2-1.12-1.9.9.jar                    | None                                     |
       | LCH   | foamfix            | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                    | None                                     |
       | LCH   | friendlyfire       | 1.5.12                   | FriendlyFire-1.12.2-1.5.12.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | minecraftfuture    | 0.1.13                   | future-mc-0.1.13.jar                          | None                                     |
       | LCH   | waila              | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | LCH   | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironchest          | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
       | LCH   | ironfurnaces       | 1.3.5                    | ironfurnaces-1.3.5.jar                        | None                                     |
       | LCH   | journeymap         | 1.12.2-5.7.0             | journeymap-1.12.2-5.7.0.jar                   | None                                     |
       | LCH   | mowziesmobs        | 1.5.4                    | mowziesmobs-1.5.4.jar                         | None                                     |
       | LCH   | openmods           | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCH   | openblocks         | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCH   | harvestcraft       | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar               | None                                     |
       | LCH   | patchouli          | 1.0-20                   | Patchouli-1.0-20.jar                          | None                                     |
       | LCH   | xreliquary         | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                | None                                     |
       | LCH   | somanyenchantments | 0.4.4                    | So Many Enchantments V0.4.4.jar               | None                                     |
       | LCH   | specialmobs        | 1.0.2_for_mc1.12.2       | specialmobs-1.0.2_for_mc1.12.2.jar            | None                                     |
       | LCH   | stg                | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                          | None                                     |
       | LCH   | storagedrawers     | 1.12.2-5.4.1             | StorageDrawers-1.12.2-5.4.1.jar               | None                                     |
       | LCH   | twilightforest     | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | LCH   | vanillafix         | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCH   | yamda              | 0.0.0.yamda              | YAMDA-1.0.2.jar                               | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
  Suspected Mods: Chocolate Quest Repoured Mod (cqrepoured)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by DerToaster98** [comment]
please use the issue template. this is barely readable

**Comment by DerToaster98** [comment]
however, this will be fixed in the next update

**Comment by DerToaster98** [comment]
is fixed in newest version
