### ISSUE TITLE
game keeps crashing when im in the end

### ISSUE THREAD

**Issue by madguyreally** [TeamChocoQuest/ChocolateQuestRepoured#164]
and it keeps giving this crash report 
- Minecraft Crash Report ----
// Daisy, daisy...

Time: 27.3.2020 21:54
Description: Error loading dungeon caveTests.prop from missing folder: \AppData\Roaming\.minecraft\config\Chocolate\snowCastles

java.lang.NullPointerException: Error loading dungeon caveTests.prop from missing folder: AppData\Roaming\.minecraft\config\Chocolate\snowCastles
	at com.chocolate.chocolateQuest.builder.BuilderHelper.getRandomNBTMap(BuilderHelper.java:669)
	at com.chocolate.chocolateQuest.builder.BuilderTemplate.generate(BuilderTemplate.java:55)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generateBigDungeon(WorldGeneratorNew.java:150)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generateSurface(WorldGeneratorNew.java:100)
	at com.chocolate.chocolateQuest.WorldGeneratorNew.generate(WorldGeneratorNew.java:62)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 703529000 bytes (670 MB) / 1006632960 bytes (960 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) 
	UCHIJAAAA	ss3dMinimap{0} [ss3dMinimap] (3dMinimap-172-1.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) 
	UCHIJAAAA	Morph{0.9.0} [Morph] (Morph-Beta-0.9.0.jar) 
	UCHIJAAAA	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	telepads{1.6.4 v5} [Teleportation Pads] (Telepads-1.7.2_1.7.jar) 
	UCHIJAAAA	dna948{1.35} [The Last Sword You Will Ever Need Mod] (The_Last_Sword_You_Will_Ever_Need_Mod-1.10.jar) 
	UCHIJAAAA	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-1.7.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['aQINX'/342, l='pls good rng world', x=-22,48, y=63,00, z=48,20]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

i've downloaded the newest versions and it wont work and i also cant disable or delete the mod for some reason

**Comment by DerToaster98** [comment]
No support for cqc. This github is for cqr. For cqc use the cqc discord channels
