### ISSUE TITLE
Lacking Dependencies

### ISSUE THREAD

**Issue by tarius30** [TeamChocoQuest/ChocolateQuestRepoured#171]
**Describe the bug**

A clear and concise description of what the bug is:

Upon loading the game, I receive an error message notifying me that I must include the right dependencies for Chocolate Quest Repoured Mod (llibrary 1.17.9 (missing)).

I see when posting this question that there has been a similar question before and that there might be a separate file I need to download an put in the mods folder (the llibrary file). Is this true? I do not see such file in the files tab on Curse.

Thanks in advance!

**To Reproduce**

I have installed and ran the following versions of minecraft:

1.15
1.7.10
1.7.10 Forge
1.7.12
1.7.12 Forge (pathed to CQR folder)

Installed the following mods (aside from Forge)

Fastcraft
LOTR Mod (1.7.10)
CQR

**Expected behavior**

To play the game.

**Screenshots**

**Versions**
Chocolate Quest Repoured: 1.12.2-1.13.1A.jar
Forge: 1.12.2-forge-14.23.5.2852
Minecraft: 1.12.2

**Other**

[09:16:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:16:55] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2852 for Minecraft 1.12.2 loading
[09:16:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\raram\Downloads\runtime\jre-x64
[09:16:55] [main/INFO] [FML]: Searching C:\Users\raram\AppData\Roaming\.minecraft\CQR\mods for mods
[09:16:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:16:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:16:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[09:16:57] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[09:16:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:16:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:16:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:16:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:16:57] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:16:58] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: Tarius30
[09:17:02] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[09:17:03] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 514625632 bytes (490 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6999' Renderer: 'Intel(R) UHD Graphics 620'
[09:17:03] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2852 Initialized
[09:17:03] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[09:17:03] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[09:17:03] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[09:17:03] [Client thread/INFO] [FML]: Searching C:\Users\raram\AppData\Roaming\.minecraft\CQR\mods for mods
[09:17:04] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[09:17:04] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod cqrepoured (Chocolate Quest Repoured Mod) requires [llibrary@[1.7.19,1.7.19]]
[09:17:04] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod cqrepoured (Chocolate Quest Repoured Mod) requires [llibrary@[1.7.19,1.7.19]]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:17:04] [Client thread/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[09:17:04] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Chocolate Quest Repoured Mod
[09:17:04] [Client thread/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[09:17:05] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[09:17:05] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 77379400 nanos
[09:17:05] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[09:17:05] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[09:17:06] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[09:17:06] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[09:17:06] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded

**Comment by DerToaster98** [comment]
1) There isnt a 1.7.12
2) Forge version is too old, use 2847
3) you are missing llibrary

**Comment by tarius30** [comment]
I have downloaded 2847 (note that 2847 is older than 2852).
Where do I get the library?    On Wednesday, April 8, 2020, 09:34:50 AM CDT, DerToaster98 <notifications@github.com> wrote:  
 
 

   
   - There isnt a 1.7.12
   - Forge version is too old, use 2847
   - you are missing llibrary

**Comment by DerToaster98** [comment]
1) 2852 is bugged
2) [https://lmgtfy.com/?q=llibrary+1.12.2+download]

**Comment by tarius30** [comment]
Thank you. I was not aware that 1.12.2 Library was a separate stand-alone download that must be added as if it were a separate mod.
    On Wednesday, April 8, 2020, 01:51:34 PM CDT, DerToaster98 <notifications@github.com> wrote:  
 
 

   
   - 2852 is bugged
   - [https://lmgtfy.com/?q=llibrary+1.12.2+download]
