### ISSUE TITLE
Cursed Bone Crash

### ISSUE THREAD

**Issue by Lucky130909** [TeamChocoQuest/ChocolateQuestRepoured#177]
**Describe the bug**
Simply using the Cursed Bone item causes my game to crash.
**To Reproduce**
1. Open inventory (Creative, because then it's faster)
2. Get Cursed Bone Item 
3. See error

**Expected behavior**

**Screenshots**
If anything, the picture of the item itself, as soon as I use it, minecraft crashes

**Versions**
Chocolate Quest Repoured: Alpha20
Forge: forge-1.12.2-14.23.5.2846
Minecraft: 1.12.2

**Other**
Crash report:
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 4/21/20 12:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chocolate Quest Repoured Mod (cqrepoured)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.teamcqr.chocolatequestrepoured.util.PropertyFileHelper.getIntArrayProperty(PropertyFileHelper.java:57)
	at com.teamcqr.chocolatequestrepoured.structuregen.DungeonBase.<init>(DungeonBase.java:97)
	at com.teamcqr.chocolatequestrepoured.structuregen.dungeons.DefaultSurfaceDungeon.<init>(DefaultSurfaceDungeon.java:32)
	at com.teamcqr.chocolatequestrepoured.structuregen.DungeonRegistry.getDungeonByType(DungeonRegistry.java:160)
	at com.teamcqr.chocolatequestrepoured.structuregen.DungeonRegistry.loadDungeonFiles(DungeonRegistry.java:79)
	at com.teamcqr.chocolatequestrepoured.structuregen.DungeonRegistry.loadDungeons(DungeonRegistry.java:275)
	at com.teamcqr.chocolatequestrepoured.CQRMain.postInit(CQRMain.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 879672768 bytes (838 MB) / 1223163904 bytes (1166 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xms256M -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                    | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft  | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJ | mcp        | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJ | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2846-universal.jar   | None                                     |
	| LCHIJ | forge      | 14.23.5.2846 | forge-1.12.2-14.23.5.2846-universal.jar   | None                                     |
	| LCHIJ | llibrary   | 1.7.19       | llibrary-1.7.19-1.12.2.jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIE | cqrepoured | 1.10.0A      | ChocolateQuestRepoured-1.12.2-1.10.0A.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.74' Renderer: 'GeForce GTX 1080/PCIe/SSE2'

Log file: N/A
Singleplayer/Multiplayer: Both
Other mods (that are necessary to produce the bug): In Modpack, then reproduced with just Chocolate Quest
Other mods (that are also installed):

**Comment by Meldexun** [comment]
So in the crash report that you uploaded it says the game crashed during loading. But that doesn't matter your version of CQR is very outdated.

**Comment by Lucky130909** [comment]
Really? On cursed forage it is the latest version... Could you possibly
give me a link to the latest version that would work on 1.12.2?
Also, thank you so much for replying so quickly, you're a great
devloper for that alone!

**Comment by Meldexun** [comment]
Since you answered per email you couldn't see that i edited my message. I looked at the crash report and there it said that you are using Alpha 16 (v1.10.0). Nonetheless when you are using Alpha 20 (v1.14.0) then it is the newest and we need a crash report (the one you sent has nothing to do with the cursed bone and doesn't use Alpha 20).

**Comment by Lucky130909** [comment]
I actually found a version where it is Alpha 20:
https://paste.dimdev.org/uzaqoteget.mccrash
I realise that in this one there are other mods installed, however this crash has been replicated with just Chocolate Quest installed as well.

**Comment by Meldexun** [comment]
That bug is already know. Tomorrow there will probably be a new release.

**Comment by DerToaster98** [comment]
> I actually found a version where it is Alpha 20:
> https://paste.dimdev.org/uzaqoteget.mccrash
> I realise that in this one there are other mods installed, however this crash has been replicated with just Chocolate Quest installed as well.

That crash isnt related with the cursed bone. Also just searching for a different crash report that is not your crash doesnt help us. Please PROPERLY send a crash report. This means: download the latest build (alpha20), follow the update instructions in the changelog, launch the game, try to reproduce the crash like you claim it can be reproduced.

Also „curseforge states alpha16=latest version“ is just wrong. I just checked and it shows me alpha 20 as the latest build. Also if you download it from a different place than curseforge, github or our discord: we dont support these sites and they very probably dont even have the permission of us to upload our mod on their site

**Comment by DerToaster98** [comment]
Also you should use forge 2847, you use 2846. we recommend you to use 2847 and dont support other forge versions at the moment

**Comment by Meldexun** [comment]
Is fixed.
