### ISSUE TITLE
Crash in server while dungeon generate

### ISSUE THREAD

**Issue by SweetyCurves** [TeamChocoQuest/ChocolateQuestRepoured#182]
I test if the game dont crash in client, and the structures generate well, but mean while i add this mod to my personal server, the server crash and say that

Time: 24/04/20 6:07
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 134217727
	at com.teamcqr.chocolatequestrepoured.structuregen.generation.Structure.updateLiquids(Structure.java:235)
	at com.teamcqr.chocolatequestrepoured.structuregen.generation.Structure.isGenerated(Structure.java:192)
	at com.teamcqr.chocolatequestrepoured.structuregen.generation.DungeonGenerationManager.tick(DungeonGenerationManager.java:150)
	at com.teamcqr.chocolatequestrepoured.structuregen.generation.DungeonGenerationManager.handleWorldTick(DungeonGenerationManager.java:65)
	at com.teamcqr.chocolatequestrepoured.structuregen.generation.DungeonGenerationEventHandler.onWorldTickEvent(DungeonGenerationEventHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_DungeonGenerationEventHandler_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

If u need all crash report i can send u. If u can fix this problem it will be awesome, because i was waiting for this mod a lot of years and community and me want to play this mod with friends

**Comment by DerToaster98** [comment]
Invalid, please use the issue template correctly, the report is pretty much useless like it is now.

**Comment by SweetyCurves** [comment]
I spent 20 minutes trying to learn how to do that and i couldn't. Its my first issue in github, sorry for the problems.

**Comment by DerToaster98** [comment]
1) Please properly report bugs the next time
2) This will be fixed in the next build (actually it is patched in the codebase, but that was done after the latest build got released)
