### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by Regrad** [TeamChocoQuest/ChocolateQuestRepoured#184]
Client crash

    at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.isSpellAnimated(AbstractEntityCQR.java:1131)
    at com.teamcqr.chocolatequestrepoured.objects.entity.bases.AbstractEntityCQR.onUpdate(AbstractEntityCQR.java:511)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)

https://pastebin.com/hWSnR1uN

**Comment by DerToaster98** [comment]
Not acceptable, issue will be closed. use the issue template
