### ISSUE TITLE
1.12.2 Server crash report

### ISSUE THREAD

**Issue by Loxera** [TeamChocoQuest/ChocolateQuestRepoured#194]
**Common sense Info**
 - I play...
   - [ ] With a large modpack
   - [x] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [X] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The SERVER crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured:
Forge: 1.12.2-14.23.5.2854
Minecraft: 1.12.2

**Describe the bug**

I open my server and it crashes.

https://i.imgur.com/OkUJcqm.png

**Expected behavior**

I wanted the server to work perfectly

**Screenshots**
https://i.imgur.com/OkUJcqm.png

**Other**
Crash report: "---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 21/05/20 22:37
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at com.teamcqr.chocolatequestrepoured.init.ModItems$ItemRegistrationHandler.registerItems(ModItems.java:336)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_ItemRegistrationHandler_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.model.ModelBiped
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3543599560 bytes (3379 MB) / 4019716096 bytes (3833 MB) up to 4019716096 bytes (3833 MB)
	JVM Flags: 2 total; -Xmx4000M -Xms4000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                    | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft  | 1.12.2       | minecraft.jar                             | None                                     |
	| LCH   | mcp        | 9.42         | minecraft.jar                             | None                                     |
	| LCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | llibrary   | 1.7.19       | llibrary-1.7.19-1.12.2.jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | cqrepoured | 1.18.0A      | ChocolateQuestRepoured-1.12.2-1.18.0A.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)"
.
Log file: I just created an account to contact you, I never used GitTub and I don't know how to attach files.
Singleplayer/Multiplayer: m
Other mods (that are necessary to produce the bug):
Other mods (that are also installed):

**Comment by DerToaster98** [comment]
Attach the log as a FILE and not just "copy paste text goes spam spam" please

**Comment by DerToaster98** [comment]
Also use the latest version, that bug was fixed in v1.18.1

**Comment by DerToaster98** [comment]
Claused cause of the bug reporter being unwilling to interact and be cooperative on this
