### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by GretixYT** [TeamChocoQuest/ChocolateQuestRepoured#230]
My server with this mod randomly crashes with this in logs:

[15:38:59] [CQR Dungeon Generator Thread/INFO] [cqrepoured]: Start generating dungeon RandomizedCastles at BlockPos{x=-1176, y=78, z=216}
[15:39:00] [CQR Dungeon Generator Thread/WARN] [cqrepoured]: Placed a chest but could not find a loot table for Room Type BEDROOM_BASIC
[15:39:00] [CQR Dungeon Generator Thread/WARN] [cqrepoured]: Placed a chest but could not find a loot table for Room Type ALCHEMY_LAB
[15:39:00] [CQR Dungeon Generator Thread/WARN] [cqrepoured]: Placed a chest but could not find a loot table for Room Type ALCHEMY_LAB
[15:39:00] [CQR Dungeon Generator Thread/ERROR] [cqrepoured]: Failed to prepare dungeon RandomizedCastles for generation at BlockPos{x=-1176, y=78, z=216}
java.lang.NullPointerException: null
	at java.util.TreeMap.rotateRight(TreeMap.java:2243) ~[?:1.8.0_272]
	at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2275) ~[?:1.8.0_272]
	at java.util.TreeMap.put(TreeMap.java:582) ~[?:1.8.0_272]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:1.8.0_272]
	at net.minecraft.world.WorldServer.scheduleBlockUpdate(WorldServer.java:594) ~[oo.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:521) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.getChunk(World.java:310) ~[amu.class:?]
	at net.minecraft.entity.Entity.setPositionAndRotation(Entity.java:1400) ~[vg.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.rooms.decoration.paintings.RoomDecorPainting.createEntityDecoration(RoomDecorPainting.java:57) ~[RoomDecorPainting.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.rooms.decoration.paintings.RoomDecorPainting.build(RoomDecorPainting.java:48) ~[RoomDecorPainting.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.rooms.decoration.paintings.RoomDecorPainting.buildRandom(RoomDecorPainting.java:37) ~[RoomDecorPainting.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.rooms.CastleRoomDecoratedBase.addWallDecoration(CastleRoomDecoratedBase.java:187) ~[CastleRoomDecoratedBase.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.rooms.CastleRoomDecoratedBase.decorate(CastleRoomDecoratedBase.java:48) ~[CastleRoomDecoratedBase.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.CastleRoomSelector.addDecoration(CastleRoomSelector.java:185) ~[CastleRoomSelector.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.castleparts.CastleRoomSelector.generate(CastleRoomSelector.java:154) ~[CastleRoomSelector.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.GeneratorCastle.buildStructure(GeneratorCastle.java:51) ~[GeneratorCastle.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.generators.AbstractDungeonGenerator.generate(AbstractDungeonGenerator.java:46) [AbstractDungeonGenerator.class:?]
	at com.teamcqr.chocolatequestrepoured.structuregen.DungeonGeneratorThread.run(DungeonGeneratorThread.java:33) [DungeonGeneratorThread.class:?]
[15:39:01] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327) ~[?:1.8.0_272]
	at java.util.TreeMap.firstKey(TreeMap.java:290) ~[?:1.8.0_272]
	at java.util.TreeSet.first(TreeSet.java:394) ~[?:1.8.0_272]
	at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:704) ~[oo.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:223) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
[15:39:01] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/minecraft/./crash-reports/crash-2020-10-30_15.39.01-server.txt
[15:39:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[15:39:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[15:39:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[15:39:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[15:39:01] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Tropics
[15:39:01] [Server thread/INFO] [cqrepoured]: Saved 0 parts to generate
[15:39:02] [Server thread/INFO] [cqrepoured]: Saved 0 parts to generate
[15:39:02] [Server thread/INFO] [STDOUT]: [atomicstryker.minions.common.MinionsCore:getMinionMap:336]: Minions: minionMapLock was hanging
[15:39:02] [Server thread/INFO] [FML]: Unloading dimension 0
[15:39:02] [Server thread/INFO] [FML]: Unloading dimension -127
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -20
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -21
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -15
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -22
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -13
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -18
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -19
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -16
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -17
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1505
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1503
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1501
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1506
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1511
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1500
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1509
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1502
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1507
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1508
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1510
[15:39:02] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1504
[15:39:02] [pool-3-thread-3/INFO] [FML]: Stop ReadRunnable
[15:39:02] [pool-3-thread-1/INFO] [FML]: Stop ReadRunnable
[15:39:02] [pool-3-thread-2/INFO] [FML]: Stop ReadRunnable
[15:39:02] [pool-3-thread-4/INFO] [FML]: Stop ReadRunnable
[15:39:02] [pool-3-thread-6/INFO] [FML]: Stop ReadRunnable
[15:39:02] [pool-3-thread-5/INFO] [FML]: Stop SplitterRunnable
[15:39:02] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by DerToaster98** [comment]
This report is useless. It is missing any information we need to work on this. 
Please create a new issue ticket, use the issue template and fill it out correctly.

Closing this issue now.
