### ISSUE TITLE
OpenGL Error 1283, VanillaFix Says This Mod is the Culprit. 

### ISSUE THREAD

**Issue by popepenguin** [TeamChocoQuest/ChocolateQuestRepoured#242]
**Common sense Info**
 - I play...
   - [x] With a large modpack
 - The issue occurs in...
   - [x] Singleplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 
 

Chocolate Quest Repoured: 1.12.2 - 2.2.1B
Forge: 1.12.2 - 14.23.5.2854
Minecraft: 1.12.2

I'm using a collection of mods, the main one being Vics Modern Warfare. Blocks and Mobs such as Pirates, doors, and beds start floating around the screen, glitching out. Impossible to shoot, and causes the game to redirect to the following: 
![2021-01-10_21 16 42](https://user-images.githubusercontent.com/59899047/104142431-90ce5b80-5389-11eb-82aa-187cd3c5c1c4.png)

Only happens when you start shooting the dungeon mobs and bosses. Happens often when ADSing while in combat. 
other images:
![2021-01-10_21 13 56](https://user-images.githubusercontent.com/59899047/104142439-9a57c380-5389-11eb-9417-c6e075f1dc4f.png)
![2021-01-10_21 14 00](https://user-images.githubusercontent.com/59899047/104142442-9cba1d80-5389-11eb-802a-9749c21824ca.png)

Steps to Reproduce:
1. Go to a dungeon, or spawn one in (I use the airship often)
2. Take a gun from Vics Modern Warfare (Any should do, the automatics reproduce best) 
3. Start shooting at bosses, mobs, etc. 
4. Glitch should occur

**Expected behavior**
Expected this to not occur
Things should start glitching out, and a notification saying to ctrl-i should appear. 

**Other**
 - Other mods (that are necessary to produce the bug): Vics Modern Warfare, Optifine
 - Other mods (that are also installed): 
![image](https://user-images.githubusercontent.com/59899047/104142525-fde1f100-5389-11eb-953d-b2bc4d372020.png)

Latest Log: 
[correctlog.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/5793871/correctlog.txt)

**Comment by Meldexun** [comment]
1. 'latest' is not a valid version. Often people think they use the latest version of a mod when actually they are not. So saying 'latest' just makes bug fixing more complicated.
2. Please provide the crash report and the latest log.

**Comment by popepenguin** [comment]
Updated the version, and added the latest log.  There's no crash log as the bug doesn't crash the game.

**Comment by popepenguin** [comment]
also, this
![image](https://user-images.githubusercontent.com/59899047/104145156-fc1d2b00-5393-11eb-86ad-efcae68dd286.png)

**Comment by DerToaster98** [comment]
At first: in general do not trust the vanillafix

Also when reading the error log it looks more like Vics Modern Warfare is the problem. It looks like it makes some adjustments to HeldItem-Rendering and thus assumes that every entity that holds items is biped, which is not the case for our parrot. It can hold items and is not biped. This assumption on viks side causes a lot of cast exceptions which probably leads to the „error“.

However there also seems to be a small problem on our side which however isn’t related to the problem described here.

**Comment by DerToaster98** [comment]
You should report to vics that they should not assume every entity that uses the "LayerHeldItem" layer has a biped model.

This is the exact error for them:
`[21:13:52] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: net.minecraft.client.model.ModelParrot cannot be cast to net.minecraft.client.model.ModelBiped
	at com.vicmatskiv.weaponlib.compatibility.Interceptors.positionItemSide(Interceptors.java:265) ~[Interceptors.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerHeldItem.renderHeldItem(LayerHeldItem.java:58) ~[ccc.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerHeldItem.doRenderLayer(LayerHeldItem.java:41) ~[ccc.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.renderLayers(RenderLivingBase.java:561) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:270) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(RenderLiving.java:50) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(RenderLiving.java:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.redirect$zbo000$renderEntityStatic(RenderGlobal.java:3753) [buy.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:849) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1801) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

The problem is: Our pirate parrot can hold items, and it renders them by using a subclass of "LayerHeldItem", but we only adjust the render height there. Vic's seem to make some adjustations to "LayerHeldItem", these lead to the error cause it looks like they assume that the model of the entity used there is either a Biped one or a subclass of it. And "ModelParrot" (model of our parrot) isn't a subclass of Biped.
