### ISSUE TITLE
Weird Block Crash with Openblocks

### ISSUE THREAD

**Issue by mxnmnm** [TeamChocoQuest/ChocolateQuestRepoured#315]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
**Describe the bug**
My friend tried to place a sprinkler from openblocks on a random block and it caused him to crash. 

**To Reproduce**
i'm not sure how to reproduce it because he also randomly got the same crash when he got damaged by a cactus while holding an openblocks tank

 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 2.6.3B
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Open blocks

**Log File**
https://gist.github.com/mxnmnm/7354e8ba64c93505b489fc1eb1dbcae6

**Comment by Raptor22a** [comment]
I'm having a similar issue with the ICBM mod, whenever I try to place down an explosives block. It was working fine in CQR v 1.12.2-2.1.3B.

The latest update (2.6.3B, Forge 14.23.5.2860, MC 1.12.2) seems to have a HUGE conflict with the ICBM mod and a few others. Whenever I try to place down an explosives block from the ICBM mod, the game crashes. From what I can make out from the crash log, it seems to point the finger at CQR's "sayNoToPlacingBlocksNearBosses" event handler... even though I was nowhere near any dungeons.

> Description: Unexpected error
java.lang.NullPointerException: Unexpected error
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:41)
	
**at team.cqr.cqrepoured.event.EventsHandler.sayNoToPlacingBlocksNearBosses(EventsHandler.java:248)**
	
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_EventsHandler_sayNoToPlacingBlocksNearBosses_EntityPlaceEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onBlockPlace(ForgeEventFactory.java:169)
	at net.minecraft.world.World.func_190527_a(World.java:3176)
	at icbm.classic.prefab.item.ItemBlockAbstract.canPlace(ItemBlockAbstract.java:91)
	at icbm.classic.prefab.item.ItemBlockAbstract.func_180614_a(ItemBlockAbstract.java:53)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.redirect$zzo000$rightClickBlockProxy(Minecraft.java:3362)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


I can post the full log file if you need more information. I'm hoping that this can be patched, as I use the ICBM mod quite frequently to destroy dungeons once I have completed them (or as part of an artillery barrage before charging in to fight the boss). Not being able to use it anywhere any more would really suck - I don't want to have to give up either mod. It might be worth noting that it was working just fine with CQR before I updated to the more recent versions (I was previously on CQR version 1.12.2-2.1.3B)

**Comment by DerToaster98** [comment]
the problem here is not cqr but other mod's returning null for things cause they think this is funny or something.

Anyway, we have a fix for this but it does not have priority for us.
Temporarily you could disable that certain feature in the config, that should prevent the crash.

**Comment by DerToaster98** [comment]
Patched in v2.6.4B
