### ISSUE TITLE
hi guys idk whats causing the crashing i think is chocolatequest butt im not to shore can you guys pls help me thank you 

### ISSUE THREAD

**Issue by kikosun777** [TeamChocoQuest/ChocolateQuestRepoured#317]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/9/22 10:55 AM
Description: Exception getting block type in world

java.lang.NoSuchMethodError: ivorius.ivtoolkit.maze.components.MazeRooms.neighbors(Livorius/ivtoolkit/maze/components/MazeRoom;)Ljava/util/Set;
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.addMissingExits(WorldGenMaze.java:164)
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.transformedComponent(WorldGenMaze.java:150)
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.transformedComponents(WorldGenMaze.java:129)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.getPlacedRooms(TileEntityMazeGenerator.java:160)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.prepareInstanceData(TileEntityMazeGenerator.java:111)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.prepareInstanceData(TileEntityMazeGenerator.java:41)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:255)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:56)
	at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93)
	at ivorius.reccomplex.worldgen.StructureGenerator.randomInstantly(StructureGenerator.java:71)
	at ivorius.reccomplex.worldgen.WorldGenStructures.generate(WorldGenStructures.java:84)
	at ivorius.reccomplex.events.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:60)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_361_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:377)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.block.BlockStaticLiquid.func_149674_a(SourceFile:39)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at WorldServerOF.func_147456_g(WorldServerOF.java:477)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.addMissingExits(WorldGenMaze.java:164)
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.transformedComponent(WorldGenMaze.java:150)
	at ivorius.reccomplex.structures.generic.maze.WorldGenMaze.transformedComponents(WorldGenMaze.java:129)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.getPlacedRooms(TileEntityMazeGenerator.java:160)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.prepareInstanceData(TileEntityMazeGenerator.java:111)
	at ivorius.reccomplex.blocks.TileEntityMazeGenerator.prepareInstanceData(TileEntityMazeGenerator.java:41)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:255)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:56)
	at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93)
	at ivorius.reccomplex.worldgen.StructureGenerator.randomInstantly(StructureGenerator.java:71)
	at ivorius.reccomplex.worldgen.WorldGenStructures.generate(WorldGenStructures.java:84)
	at ivorius.reccomplex.events.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:60)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_361_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:377)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (1106,7,-1713), Chunk: (at 2,0,15 in 69,-108; contains blocks 1104,0,-1728 to 1119,255,-1713), Region: (2,-4; contains chunks 64,-128 to 95,-97, blocks 1024,0,-2048 to 1535,255,-1537)
Stacktrace:
	at net.minecraft.block.BlockStaticLiquid.func_149674_a(SourceFile:39)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at WorldServerOF.func_147456_g(WorldServerOF.java:477)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['kikosun'/85, l='New World', x=1153.63, y=93.21, z=-1578.77]]
	Chunk stats: ServerChunkCache: 1425 Drop: 0
	Level seed: -6027632891572570913
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10444 game time, 10444 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 132687 (now: false), thunder time: 58290 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9389757912 bytes (8954 MB) / 12985565184 bytes (12384 MB) up to 14965276672 bytes (14272 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx14272M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.3.2} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.3.2.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	heart{2.0.1} [Heart Health] ([MC1.7.10]Hearts-2.0.1.54_R.jar) 
	UCHIJAAAA	aether_legacy{v1.1.2.1} [The Aether] (aether-1.7.10-v1.1.2.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania+r1.8-249.jar) 
	UCHIJAAAA	Avaritia{1.13} [Avaritia] (Avaritia-1.13.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.0} [Better Builder's Wands] (BetterBuildersWands-0.8.0-1.7.10r89+339bc1f.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	gomc{1.0} [God Of Minecraft] (God+of+Minecraft+Mod-1.7.10-1.9.jar) 
	UCHIJAAAA	godzillamod{1.6.6} [Godzilla Mod] (Godzilla Mod-1.7.10-1.6.6.jar) 
	UCHIJAAAA	goodnightsleep{0.0.2} [Good Night's Sleep] (good-nights-sleep-1.7.10-v0.0.2.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (Hardcore-Ender-Expansion-Mod-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.4.9.9} [Inventory Pets] (inventorypets-1.7.10-1.4.9.9-universal.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	ism{2.6.1 MC-1.7.10} [Instant Structures Mod (ISM)] (ism-2.6.1 MC-1.7.10.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	UCHIJAAAA	ManaitaPlus{1.4.8} [Manaita Plus] (Manaita Plus-1.4.8.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) 
	UCHIJAAAA	Mo' Shiz{1.62.1} [Mo' Shiz] (Mo'+Shiz+v1.62.1.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.7.10-1.3.1.jar) 
	UCHIJAAAA	nevermine{Tslat-1.1.2} [Advent of Ascension] (Nevermine-Tslat-1.1.2.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (1).jar) 
	UCHIJAAAA	pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.1.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UCHIJAAAA	reccomplex{0.9.6.3} [Recurrent Complex] (RecurrentComplex-0.9.6.3.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	dna948{1.35} [The Last Sword You Will Ever Need Mod] (The_Last_Sword_You_Will_Ever_Need_Mod-1.10.jar) 
	UCHIJAAAA	tlauncher_custom_cape_skin{1.0} [TLSkinCape] (tlskincape_1.7.10-1.4.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['kikosun'/85, l='New World', x=1153.63, y=93.21, z=-1578.77]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.10.28 27.20.1028.1
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by DerToaster98** [comment]
We are not the devs or maintainers of cq on 1.7.10

looks like recurrent complex is the problem though

**Comment by kikosun777** [comment]
> We are not the devs or maintainers of cq on 1.7.10
> 
> looks like recurrent complex is the problem though
thank you so much it worked your a legend
